services:
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    container_name: tochiman-web-front
    ports:
      - 3000:3000
    volumes:
      - ./:/app
      - /app/frontend/node_modules
    env_file:
      - .env
    init: true