apiVersion: apps/v1
kind: Deployment
metadata:
  name: tochiman-com-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tochiman-com-deploy
  template:
    metadata:
      labels:
        app: tochiman-com-deploy
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
          - containerPort: 3000