name: Docker Build and Push

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: デプロイする環境
        required: true
        options:
          - 開発
          - 本番

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  REGISTRY: ghcr.io
  USER: tochiman
  IMAGE_NAME_FRONT: front-image
  FILE: |-
    ${{ fromJSON('{
      "開発": "Dockerfile",
      "本番": "Dockerfile.prod"
    }')[github.event.inputs.environment] }}
jobs:
  front-build-and-push:
    runs-on: arc-tochiman-web
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Github Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.USER }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push images
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          file: ./frontend/${{ env.FILE }}
          platforms: linux/amd64,linux/arm64
          # target: ${{ env.REPOSITORY }}
          push: true
          tags: ${{ env.REGISTRY }}/${{ github.repository }}/${{ env.IMAGE_NAME_FRONT }}:${{ github.ref_name }} 
